version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project
jobs:
  install-yarn:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Configure npm
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Yarn
          command: npm install -g yarn
  build-app:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Configure npm
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - run:
          name: Check for package.json
          command: ls -l package.json || (echo 'package.json not found!' && exit 1)
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build app
          command: yarn build
workflows:
  install_and_build:
    jobs:
      - install-yarn
      - build-app:
          requires:
            - install-yarn
