version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project
jobs:
  install-yarn:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: npm install -g yarn
workflows:
  install_yarn:
    jobs:
      - install-yarn
