version: 2.1
executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.2
    working_directory: ~/project
jobs:
  install-yarn:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Configure npm
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build app
          command: |
            cd $(git rev-parse --show-toplevel)
            yarn build
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Lint code
          command: yarn lint
workflows:
  build-test-lint:
    jobs:
      - install-yarn
